# populate_categories.py
# Safely populates 4-5 products for every category in Firebase without duplicates.

from datetime import datetime
from app.services.firebase_service import get_all, create_one

COLLECTION = "products"

NEW_PRODUCTS = [
    # ── Category 1: pashtun_dress (1 product needed to reach 5) ──────────────
    {
        "name": "Waziristan Embroidered Royal Shalwar Suit",
        "description": "Handcrafted charcoal black raw silk kurta suit adorned with authentic silver thread khamak tribal collar work and cuff embroidery.",
        "price": 6800.0,
        "sku": "PAS-005",
        "category": "pashtun_dress",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "colors": ["Charcoal Black", "Slate Grey"],
        "stock": 16,
        "image_urls": ["https://images.unsplash.com/photo-1597983073750-16f5ded1321f?w=800"],
        "is_featured": True,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 5,
        "tags": ["pashtun", "embroidered", "kurta", "heritage"],
    },

    # ── Category 2: paint_shirt (3 products needed to reach 5) ───────────────
    {
        "name": "Nastaliq Calligraphy Hand-Painted Shirt",
        "description": "Artisan-painted breathable linen shirt with Pashto poetical calligraphy in deep indigo ink. Individually signed and numbered.",
        "price": 3100.0,
        "sku": "PNT-003",
        "category": "paint_shirt",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Ivory White", "Beige"],
        "stock": 20,
        "image_urls": ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800"],
        "is_featured": True,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 3,
        "tags": ["calligraphy", "artisan", "hand-painted", "linen"],
    },
    {
        "name": "Khyber Sunset Abstract Painted Shirt",
        "description": "Bold expressionist color gradient hand-painted on pure combed cotton, capturing the dusk over Khyber Pass.",
        "price": 2950.0,
        "sku": "PNT-004",
        "category": "paint_shirt",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "colors": ["Sunset Ochre", "Terracotta"],
        "stock": 18,
        "image_urls": ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800"],
        "is_featured": False,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 4,
        "tags": ["abstract", "sunset", "hand-painted", "cotton"],
    },
    {
        "name": "Tribal Paisley Hand-Painted Shirt",
        "description": "Intricate traditional paisley and floral border motif delicately brushed on premium soft cotton poplin.",
        "price": 2750.0,
        "sku": "PNT-005",
        "category": "paint_shirt",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Off-White", "Sage"],
        "stock": 22,
        "image_urls": ["https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800"],
        "is_featured": False,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 5,
        "tags": ["paisley", "tribal", "poplin", "artisan"],
    },

    # ── Category 3: wallets (4 products needed to reach 5) ────────────────────
    {
        "name": "Vintage Distressed Leather Cardholder",
        "description": "Ultra-slim front pocket minimalist cardholder crafted from vegetable-tanned pull-up saddle leather with 6 card slots and cash pocket.",
        "price": 2200.0,
        "sku": "WAL-002",
        "category": "wallets",
        "sizes": [],
        "colors": ["Cognac Tan", "Dark Espresso"],
        "stock": 25,
        "image_urls": ["https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800"],
        "is_featured": False,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 2,
        "tags": ["wallet", "cardholder", "leather", "minimalist"],
    },
    {
        "name": "Kandahari Brass Crest Long Zip Wallet",
        "description": "Spacious continental zip-around wallet with embossed Pashtun geometric motifs, antique brass zipper, and smartphone pocket.",
        "price": 4800.0,
        "sku": "WAL-003",
        "category": "wallets",
        "sizes": [],
        "colors": ["Antique Brown", "Midnight Black"],
        "stock": 14,
        "image_urls": ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=800"],
        "is_featured": True,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 3,
        "tags": ["wallet", "continental", "long-wallet", "leather"],
    },
    {
        "name": "Artisan Hand-Stitched Leather Trifold",
        "description": "Classic trifold wallet featuring waxed nylon saddle-stitching, clear ID window, and twin bill compartments for international currency.",
        "price": 3600.0,
        "sku": "WAL-004",
        "category": "wallets",
        "sizes": [],
        "colors": ["Saddle Tan", "Burgundy"],
        "stock": 18,
        "image_urls": ["https://images.unsplash.com/photo-1559563458-527698bf5295?w=800"],
        "is_featured": False,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 4,
        "tags": ["wallet", "trifold", "hand-stitched", "leather"],
    },
    {
        "name": "Carbon Fiber & Leather Money Clip Wallet",
        "description": "Modern tactical lifestyle wallet combining genuine full-grain leather with aerospace carbon fiber and an integrated spring money clip.",
        "price": 3200.0,
        "sku": "WAL-005",
        "category": "wallets",
        "sizes": [],
        "colors": ["Matte Black", "Gunmetal"],
        "stock": 20,
        "image_urls": ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=800"],
        "is_featured": False,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 5,
        "tags": ["wallet", "money-clip", "carbon-fiber", "tactical"],
    },

    # ── Category 4: lighters (4 products needed to reach 5) ───────────────────
    {
        "name": "Antique Brass Dual-Torch Jet Lighter",
        "description": "Heavyweight vintage-style brass windproof jet flame lighter with adjustable dual torches and built-in cigar punch.",
        "price": 3400.0,
        "sku": "LGT-002",
        "category": "lighters",
        "sizes": [],
        "colors": ["Antique Brass", "Aged Copper"],
        "stock": 24,
        "image_urls": ["https://images.unsplash.com/photo-1542385151-efd9000785a0?w=800"],
        "is_featured": True,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 2,
        "tags": ["lighter", "torch", "brass", "windproof"],
    },
    {
        "name": "Damascus Steel Pattern Trench Lighter",
        "description": "Classic World War style kerosene trench lighter with laser-etched Damascus steel rippled finish and sealed waterproof tank.",
        "price": 4100.0,
        "sku": "LGT-003",
        "category": "lighters",
        "sizes": [],
        "colors": ["Damascus Grey", "Silver"],
        "stock": 15,
        "image_urls": ["https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800"],
        "is_featured": False,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 3,
        "tags": ["lighter", "trench", "damascus", "vintage"],
    },
    {
        "name": "Royal Dragon Crest Gold Plasma Lighter",
        "description": "Rechargeable electric dual-arc plasma beam lighter featuring a 3D embossed royal dragon crest and touch-activated ignition.",
        "price": 3600.0,
        "sku": "LGT-004",
        "category": "lighters",
        "sizes": [],
        "colors": ["Imperial Gold", "Obsidian Black"],
        "stock": 22,
        "image_urls": ["https://images.unsplash.com/photo-1542385151-efd9000785a0?w=800"],
        "is_featured": True,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 4,
        "tags": ["lighter", "plasma", "electric", "dragon"],
    },
    {
        "name": "Stealth Matte Black Turbo Flame Lighter",
        "description": "Ergonomic matte rubberized metal body with high-altitude blue turbo flame and fuel level view window.",
        "price": 2600.0,
        "sku": "LGT-005",
        "category": "lighters",
        "sizes": [],
        "colors": ["Stealth Black", "Titanium Grey"],
        "stock": 30,
        "image_urls": ["https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800"],
        "is_featured": False,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 5,
        "tags": ["lighter", "turbo", "matte", "stealth"],
    },

    # ── Category 5: watches (5 products) ─────────────────────────────────────
    {
        "name": "Noor Royal Heritage Chronograph Watch",
        "description": "Luxury automatic chronograph with deep emerald sunburst dial, Roman numeral indices, and hand-stitched alligator embossed leather strap.",
        "price": 14500.0,
        "sku": "WAT-001",
        "category": "watches",
        "sizes": [],
        "colors": ["Emerald & Gold", "Rose Gold & Brown"],
        "stock": 8,
        "image_urls": ["https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800"],
        "is_featured": True,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 1,
        "tags": ["watch", "chronograph", "luxury", "automatic"],
    },
    {
        "name": "Khyber Black Minimalist Slim Watch",
        "description": "Ultra-thin 6mm case with sapphire crystal glass, matte black dial, and surgical grade 316L stainless steel mesh bracelet.",
        "price": 8900.0,
        "sku": "WAT-002",
        "category": "watches",
        "sizes": [],
        "colors": ["All Black", "Gunmetal Mesh"],
        "stock": 15,
        "image_urls": ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800"],
        "is_featured": False,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 2,
        "tags": ["watch", "minimalist", "slim", "black"],
    },
    {
        "name": "Sultan Skeletal Mechanical Watch",
        "description": "Self-winding transparent skeleton timepiece revealing the 21-jewel mechanical escapement inside an exhibition back case.",
        "price": 16800.0,
        "sku": "WAT-003",
        "category": "watches",
        "sizes": [],
        "colors": ["Gold & Silver Dual Tone", "Silver Skeleton"],
        "stock": 6,
        "image_urls": ["https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800"],
        "is_featured": True,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 3,
        "tags": ["watch", "skeleton", "mechanical", "luxury"],
    },
    {
        "name": "Vintage Field Pilot Leather Watch",
        "description": "Aviation-inspired rugged timepiece featuring high-contrast luminous hands, date complication, and thick bridle leather strap.",
        "price": 7500.0,
        "sku": "WAT-004",
        "category": "watches",
        "sizes": [],
        "colors": ["Khaki & Brown", "Olive Green"],
        "stock": 12,
        "image_urls": ["https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800"],
        "is_featured": False,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 4,
        "tags": ["watch", "pilot", "field", "leather"],
    },
    {
        "name": "Celestial Moonphase Calendar Watch",
        "description": "Classic dress watch featuring a functioning lunar moonphase display at 6 o'clock, day-date subdials, and sapphire dome.",
        "price": 12500.0,
        "sku": "WAT-005",
        "category": "watches",
        "sizes": [],
        "colors": ["Midnight Blue & Silver", "White & Gold"],
        "stock": 10,
        "image_urls": ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800"],
        "is_featured": True,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 5,
        "tags": ["watch", "moonphase", "calendar", "dress"],
    },

    # ── Category 6: perfumes (5 products) ────────────────────────────────────
    {
        "name": "Oud Al-Pashtun Signature Eau De Parfum",
        "description": "Regal oriental woody fragrance composed of rare Royal Cambodian oud, Taif rose, ambergris, and sweet smoky leather.",
        "price": 6500.0,
        "sku": "PRF-001",
        "category": "perfumes",
        "sizes": [],
        "colors": ["100ml / 3.4 fl oz"],
        "stock": 20,
        "image_urls": ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=800"],
        "is_featured": True,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 1,
        "tags": ["perfume", "oud", "fragrance", "oriental"],
    },
    {
        "name": "Kandahari Amber & Musk Extrait",
        "description": "Warm, enveloping, long-lasting luxury extrait featuring golden amber, white musk, cedarwood, and delicate saffron undertones.",
        "price": 5800.0,
        "sku": "PRF-002",
        "category": "perfumes",
        "sizes": [],
        "colors": ["50ml Extrait"],
        "stock": 18,
        "image_urls": ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800"],
        "is_featured": False,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 2,
        "tags": ["perfume", "amber", "musk", "luxury"],
    },
    {
        "name": "Khyber Velvet Rose Attar Oil",
        "description": "Pure concentrated alcohol-free attar oil combining Damascene velvet rose petals with aged sandalwood and cardamom.",
        "price": 4200.0,
        "sku": "PRF-003",
        "category": "perfumes",
        "sizes": [],
        "colors": ["12ml Crystal Bottle"],
        "stock": 25,
        "image_urls": ["https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800"],
        "is_featured": False,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 3,
        "tags": ["perfume", "attar", "rose", "oil"],
    },
    {
        "name": "Noor Royal Leather & Smoke EDP",
        "description": "Intense masculine signature scent blending Italian birch tar leather, spicy black pepper, vetiver, and dark bourbon vanilla.",
        "price": 6200.0,
        "sku": "PRF-004",
        "category": "perfumes",
        "sizes": [],
        "colors": ["100ml / 3.4 fl oz"],
        "stock": 16,
        "image_urls": ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800"],
        "is_featured": True,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 4,
        "tags": ["perfume", "leather", "smoke", "edp"],
    },
    {
        "name": "Sufi White Jasmine & Saffron Breeze",
        "description": "Fresh and intoxicating blend of handpicked jasmine sambac, wild mountain bergamot, Iranian saffron, and soft white wood.",
        "price": 4900.0,
        "sku": "PRF-005",
        "category": "perfumes",
        "sizes": [],
        "colors": ["100ml / 3.4 fl oz"],
        "stock": 22,
        "image_urls": ["https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800"],
        "is_featured": False,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 5,
        "tags": ["perfume", "jasmine", "saffron", "fresh"],
    },

    # ── Category 7: accessories (5 products) ─────────────────────────────────
    {
        "name": "Heritage Pashtun Silver Lapis Cufflinks",
        "description": "Handcrafted 925 sterling silver cufflinks inlaid with natural Badakhshan lapis lazuli gemstones.",
        "price": 3800.0,
        "sku": "ACC-001",
        "category": "accessories",
        "sizes": [],
        "colors": ["Silver & Lapis Blue"],
        "stock": 18,
        "image_urls": ["https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=800"],
        "is_featured": True,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 1,
        "tags": ["cufflinks", "silver", "lapis", "accessories"],
    },
    {
        "name": "Kandahari Hand-Woven Silk Pocket Square",
        "description": "Pure raw silk pocket square featuring authentic geometric tribal borders hand-printed in Peshawar.",
        "price": 1800.0,
        "sku": "ACC-002",
        "category": "accessories",
        "sizes": [],
        "colors": ["Maroon & Gold", "Teal & Silver"],
        "stock": 35,
        "image_urls": ["https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800"],
        "is_featured": False,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 2,
        "tags": ["pocket-square", "silk", "accessories"],
    },
    {
        "name": "Solid Brass Tiger Head Key Hook",
        "description": "Heavy cast solid brass key hook with engraved Pashtun tribal ring and quick-release belt carabiner.",
        "price": 1950.0,
        "sku": "ACC-003",
        "category": "accessories",
        "sizes": [],
        "colors": ["Antique Brass"],
        "stock": 28,
        "image_urls": ["https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800"],
        "is_featured": False,
        "is_bestseller": False,
        "show_on_home": True,
        "home_order": 3,
        "tags": ["keychain", "brass", "accessories"],
    },
    {
        "name": "Full-Grain Leather Dress Belt with Brass Buckle",
        "description": "Italian vegetable-tanned full-grain leather belt with hand-burnished edges and solid forged antique brass buckle.",
        "price": 3500.0,
        "sku": "ACC-004",
        "category": "accessories",
        "sizes": ["32", "34", "36", "38", "40"],
        "colors": ["Dark Brown", "Classic Black"],
        "stock": 20,
        "image_urls": ["https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800"],
        "is_featured": True,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 4,
        "tags": ["belt", "leather", "brass", "accessories"],
    },
    {
        "name": "Onyx & Silver Prayer Beads (Tasbih)",
        "description": "Handmade 33-bead natural matte black onyx tasbih with sterling silver spacers and hand-woven silk tassel.",
        "price": 2900.0,
        "sku": "ACC-005",
        "category": "accessories",
        "sizes": [],
        "colors": ["Matte Black Onyx"],
        "stock": 24,
        "image_urls": ["https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=800"],
        "is_featured": False,
        "is_bestseller": True,
        "show_on_home": True,
        "home_order": 5,
        "tags": ["tasbih", "onyx", "silver", "accessories"],
    },
]


def populate():
    existing = get_all(COLLECTION)
    existing_names = set(p.get("name", "").strip().lower() for p in existing)
    print(f"Found {len(existing)} existing products.")

    added = 0
    skipped = 0
    now = datetime.utcnow().isoformat()

    for item in NEW_PRODUCTS:
        name_key = item["name"].strip().lower()
        if name_key in existing_names:
            print(f"  [SKIP] Already exists: {item['name']}")
            skipped += 1
            continue

        item_data = dict(item)
        item_data["created_at"] = now
        item_data["updated_at"] = now
        created = create_one(COLLECTION, item_data)
        print(f"  [ADDED] {item['category']} -> {item['name']} (ID: {created.get('id')})")
        existing_names.add(name_key)
        added += 1

    print(f"\nFinished: {added} products added, {skipped} skipped.")
    
    # Verify final counts per category
    all_prods = get_all(COLLECTION)
    from collections import Counter
    counts = Counter(p.get("category") for p in all_prods)
    print("\nFinal Category Counts:")
    for cat, count in sorted(counts.items()):
        print(f"  {cat}: {count} products")


if __name__ == "__main__":
    populate()
